import { getDoctorRecords as getMedicalRecords } from '@/api/doctor';
import useFetch from '@/hooks/useFetch';
import Card, { CardHeader } from '@/components/ui/Card';
import Spinner from '@/components/ui/Spinner';
import EmptyState from '@/components/ui/EmptyState';
import ErrorState from '@/components/ui/ErrorState';
import { FileText, ExternalLink, FlaskConical, Heart, Scan, Syringe,
         ClipboardList, FileCheck, Download } from 'lucide-react';
import { format } from 'date-fns';

const TYPE_META = {
  'medical-history':  { icon: ClipboardList, bg: 'bg-blue-100',    text: 'text-blue-600',    label: 'Medical History' },
  'patient-profile':  { icon: FileCheck,     bg: 'bg-slate-100',   text: 'text-slate-600',   label: 'Patient Profile' },
  'doctor-notes':     { icon: ClipboardList, bg: 'bg-purple-100',  text: 'text-purple-600',  label: 'Doctor Notes' },
  'diagnosis':        { icon: FileText,      bg: 'bg-red-100',     text: 'text-red-600',     label: 'Diagnosis' },
  'scan':             { icon: Scan,          bg: 'bg-cyan-100',    text: 'text-cyan-600',    label: 'Scan' },
  'lab-result':       { icon: FlaskConical,  bg: 'bg-amber-100',   text: 'text-amber-600',   label: 'Lab Result' },
  'xray':             { icon: Scan,          bg: 'bg-indigo-100',  text: 'text-indigo-600',  label: 'X-Ray' },
  'blood-test':       { icon: FlaskConical,  bg: 'bg-rose-100',    text: 'text-rose-600',    label: 'Blood Test' },
  'blood-readings':   { icon: Heart,         bg: 'bg-pink-100',    text: 'text-pink-600',    label: 'Blood Readings' },
  'radio-reports':    { icon: Scan,          bg: 'bg-violet-100',  text: 'text-violet-600',  label: 'Radio Report' },
  'health-report':    { icon: FileCheck,     bg: 'bg-green-100',   text: 'text-green-600',   label: 'Health Report' },
  'vaccination':      { icon: Syringe,       bg: 'bg-teal-100',    text: 'text-teal-600',    label: 'Vaccination' },
  'referral':         { icon: FileText,      bg: 'bg-orange-100',  text: 'text-orange-600',  label: 'Referral' },
  'follow-up':        { icon: ClipboardList, bg: 'bg-lime-100',    text: 'text-lime-700',    label: 'Follow-up' },
  'bill':             { icon: FileText,      bg: 'bg-yellow-100',  text: 'text-yellow-700',  label: 'Bill' },
  'payment':          { icon: FileCheck,     bg: 'bg-emerald-100', text: 'text-emerald-600', label: 'Payment' },
};

const DEFAULT_META = { icon: FileText, bg: 'bg-slate-100', text: 'text-slate-600', label: 'Medical Record' };

const downloadRecord = (rec) => {
  const meta = TYPE_META[rec.record_type] || DEFAULT_META;
  const dateStr = rec.created_at
    ? format(new Date(rec.created_at), 'dd MMMM yyyy')
    : 'Unknown date';

  const lines = [
    'HelixaCare — Medical Record',
    '─'.repeat(40),
    `Record Type   : ${meta.label}`,
    `Record ID     : #${rec.id}`,
    `Date          : ${dateStr}`,
    rec.patient_name  ? `Patient       : ${rec.patient_name}`    : null,
    rec.appointment_id ? `Appointment   : #${rec.appointment_id}` : null,
    '─'.repeat(40),
    'Notes / Description:',
    rec.description || '(No notes recorded)',
    '─'.repeat(40),
    rec.file_url
      ? `Attached File : ${window.location.origin}/${rec.file_url.replace(/^\//, '')}`
      : '(No file attachment)',
    '',
    'This document was generated by HelixaCare.',
  ]
    .filter((l) => l !== null)
    .join('\n');

  const blob = new Blob([lines], { type: 'text/plain' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = `helixacare-record-${rec.id}-${rec.record_type}.txt`;
  a.click();
  URL.revokeObjectURL(url);
};

const DoctorMedicalRecords = () => {
  const { data, isLoading, error, refetch } = useFetch(getMedicalRecords);
  const records = data?.records || data?.data || data || [];

  return (
    <div className="animate-fade-in">
      <h1 className="page-title mb-6">Medical Records</h1>
      <Card>
        <CardHeader title="Patient Medical Records" />
        {isLoading && <div className="flex justify-center py-12"><Spinner size="lg" /></div>}
        {error && <ErrorState message={error} onRetry={refetch} />}
        {!isLoading && !error && records.length === 0 && (
          <EmptyState
            icon={FileText}
            title="No records yet"
            description="Medical records you've created for patients will appear here."
          />
        )}
        {!isLoading && !error && records.length > 0 && (
          <div className="space-y-3">
            {records.map((rec) => {
              const meta = TYPE_META[rec.record_type] || DEFAULT_META;
              const Icon = meta.icon;
              return (
                <div key={rec.id} className="p-4 rounded-xl bg-surface-subtle flex gap-4 items-start">
                  {/* Type icon */}
                  <div className={`w-9 h-9 rounded-lg ${meta.bg} flex items-center justify-center flex-shrink-0`}>
                    <Icon size={18} className={meta.text} />
                  </div>

                  {/* Main content */}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 flex-wrap">
                      <p className="font-medium text-text-primary">{meta.label}</p>
                      {rec.patient_name && (
                        <span className="text-xs text-text-muted bg-slate-100 px-2 py-0.5 rounded-full">
                          {rec.patient_name}
                        </span>
                      )}
                    </div>
                    {rec.description && (
                      <p className="text-sm text-text-secondary mt-0.5 line-clamp-2">{rec.description}</p>
                    )}
                    <p className="text-xs text-text-muted mt-1">
                      {rec.created_at ? format(new Date(rec.created_at), 'dd MMM yyyy') : '—'}
                    </p>
                  </div>

                  {/* Actions */}
                  <div className="flex items-center gap-3 flex-shrink-0 mt-0.5">
                    {rec.file_url && (
                      <a
                        href={`/${rec.file_url.replace(/^\//, '')}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="flex items-center gap-1 text-xs text-brand-600 hover:text-brand-700 font-medium"
                      >
                        <ExternalLink size={14} />
                        View
                      </a>
                    )}
                    <button
                      type="button"
                      onClick={() => downloadRecord(rec)}
                      className="flex items-center gap-1 text-xs text-brand-600 hover:text-brand-700 font-medium"
                    >
                      <Download size={14} />
                      Download
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </Card>
    </div>
  );
};

export default DoctorMedicalRecords;
