import { useState } from 'react';
import { getDoctorPrescriptions, addAppointmentPrescription } from '@/api/doctor';
import useFetch from '@/hooks/useFetch';
import Card, { CardHeader } from '@/components/ui/Card';
import Button from '@/components/ui/Button';
import Input from '@/components/ui/Input';
import Modal from '@/components/ui/Modal';
import Spinner from '@/components/ui/Spinner';
import EmptyState from '@/components/ui/EmptyState';
import ErrorState from '@/components/ui/ErrorState';
import { Pill, Plus, Download } from 'lucide-react';
import { format } from 'date-fns';
import toast from 'react-hot-toast';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';

const schema = z.object({
  appointment_id: z.string().min(1, 'Required'),
  medication: z.string().min(1, 'Required'),
  dosage: z.string().min(1, 'Required'),
  pack_limit: z.string().optional(),
  instructions: z.string().optional(),
  issued_date: z.string().min(1, 'Required'),
});

const downloadPrescription = (rx) => {
  const lines = [
    'HelixaCare — Prescription',
    '─'.repeat(40),
    `Patient    : ${rx.patient_name || `Appointment #${rx.appointment_id}`}`,
    `Medication : ${rx.medication || '—'}`,
    `Dosage     : ${rx.dosage || '—'}`,
    `Instructions: ${rx.instructions || '—'}`,
    `Pack limit : ${rx.pack_limit ?? '—'}`,
    `Issued     : ${rx.issued_date ? format(new Date(rx.issued_date), 'dd MMM yyyy') : '—'}`,
    '─'.repeat(40),
    'This document was generated by HelixaCare.',
  ].join('\n');
  const blob = new Blob([lines], { type: 'text/plain' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = `prescription-${rx.id}.txt`;
  a.click();
  URL.revokeObjectURL(url);
};

const DoctorPrescriptions = () => {
  const { data, isLoading, error, refetch } = useFetch(getDoctorPrescriptions);
  const prescriptions = data?.data || data || [];
  const [modalOpen, setModalOpen] = useState(false);

  const { register, handleSubmit, reset, formState: { errors, isSubmitting } } = useForm({
    resolver: zodResolver(schema),
  });

  const onSubmit = async (formData) => {
    const { appointment_id, ...rest } = formData;
    try {
      await addAppointmentPrescription(appointment_id, rest);
      toast.success('Prescription created');
      setModalOpen(false);
      reset();
      refetch();
    } catch (err) {
      toast.error(err.response?.data?.error || 'Failed to create prescription');
    }
  };

  return (
    <div className="animate-fade-in">
      <h1 className="page-title mb-6">Prescriptions</h1>
      <Card>
        <CardHeader
          title="Manage Prescriptions"
          action={
            <Button size="sm" onClick={() => setModalOpen(true)}>
              <Plus size={16} /> New
            </Button>
          }
        />
        {isLoading && <div className="flex justify-center py-12"><Spinner size="lg" /></div>}
        {error && <ErrorState message={error} onRetry={refetch} />}
        {!isLoading && !error && prescriptions.length === 0 && (
          <EmptyState icon={Pill} title="No prescriptions" description="Create a prescription for a patient after completing an appointment." />
        )}
        {!isLoading && !error && prescriptions.length > 0 && (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-slate-100">
                  <th className="text-left py-3 px-2 font-medium text-text-secondary">Patient</th>
                  <th className="text-left py-3 px-2 font-medium text-text-secondary">Medication</th>
                  <th className="text-left py-3 px-2 font-medium text-text-secondary">Dosage</th>
                  <th className="text-left py-3 px-2 font-medium text-text-secondary">Instructions</th>
                  <th className="text-left py-3 px-2 font-medium text-text-secondary">Issued</th>
                  <th className="py-3 px-2" />
                </tr>
              </thead>
              <tbody>
                {prescriptions.map((rx) => (
                  <tr key={rx.id} className="border-b border-slate-50 hover:bg-surface-subtle">
                    <td className="py-3 px-2 text-text-secondary">{rx.patient_name || `#${rx.appointment_id}`}</td>
                    <td className="py-3 px-2 font-medium text-text-primary">{rx.medication}</td>
                    <td className="py-3 px-2 text-text-secondary">{rx.dosage}</td>
                    <td className="py-3 px-2 text-text-secondary max-w-xs truncate">{rx.instructions || '—'}</td>
                    <td className="py-3 px-2 text-text-secondary">{rx.issued_date ? format(new Date(rx.issued_date), 'dd MMM yyyy') : '—'}</td>
                    <td className="py-3 px-2">
                      <button
                        type="button"
                        onClick={() => downloadPrescription(rx)}
                        className="flex items-center gap-1 text-xs text-brand-600 hover:text-brand-700 font-medium"
                        title="Download prescription"
                      >
                        <Download size={14} />
                        Download
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </Card>

      <Modal
        isOpen={modalOpen}
        onClose={() => { setModalOpen(false); reset(); }}
        title="New Prescription"
        footer={
          <>
            <Button variant="secondary" onClick={() => { setModalOpen(false); reset(); }}>Cancel</Button>
            <Button form="rx-form" type="submit" isLoading={isSubmitting}>Save</Button>
          </>
        }
      >
        <form id="rx-form" onSubmit={handleSubmit(onSubmit)} className="space-y-4">
          <Input label="Appointment ID" type="number" placeholder="Enter completed appointment ID" error={errors.appointment_id?.message} {...register('appointment_id')} />
          <Input label="Medication" placeholder="e.g. Amoxicillin" error={errors.medication?.message} {...register('medication')} />
          <Input label="Dosage" placeholder="e.g. 500mg twice daily" error={errors.dosage?.message} {...register('dosage')} />
          <Input label="Pack Limit" type="number" placeholder="e.g. 2" error={errors.pack_limit?.message} {...register('pack_limit')} />
          <Input label="Instructions" placeholder="Take with food" error={errors.instructions?.message} {...register('instructions')} />
          <Input label="Issued Date" type="date" error={errors.issued_date?.message} {...register('issued_date')} />
        </form>
      </Modal>
    </div>
  );
};

export default DoctorPrescriptions;
