import { useState, useEffect } from 'react';
import { getDoctorPrescriptions, addAppointmentPrescription } from '@/api/doctor';
import { getDoctorAppointments } from '@/api/appointments';
import { getMedications } from '@/api/pharmacy';
import usePaginatedFetch from '@/hooks/usePaginatedFetch';
import Card from '@/components/ui/Card';
import Button from '@/components/ui/Button';
import Input from '@/components/ui/Input';
import Modal from '@/components/ui/Modal';
import Spinner from '@/components/ui/Spinner';
import EmptyState from '@/components/ui/EmptyState';
import ErrorState from '@/components/ui/ErrorState';
import PageHeader from '@/components/ui/PageHeader';
import Pagination from '@/components/ui/Pagination';
import SearchableSelect from '@/components/ui/SearchableSelect';
import { Pill, Plus, Download } from 'lucide-react';
import { format } from 'date-fns';
import toast from 'react-hot-toast';

const downloadPrescription = (rx) => {
  const lines = [
    'HelixaCare — Prescription',
    '─'.repeat(40),
    `Patient : ${rx.patient_name || `Appointment #${rx.appointment_id}`}`,
    `Medication : ${rx.medication || '—'}`,
    `Dosage : ${rx.dosage || '—'}`,
    `Instructions: ${rx.instructions || '—'}`,
    `Refills allowed : ${rx.pack_limit ?? '—'}`,
    `Issued : ${rx.issued_date ? format(new Date(rx.issued_date), 'dd MMM yyyy') : '—'}`,
    '─'.repeat(40),
    'This document was generated by HelixaCare.',
  ].join('\n');
  const blob = new Blob([lines], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `prescription-${rx.id}.txt`;
  a.click();
  URL.revokeObjectURL(url);
};

const emptyForm = { appointment_id: '', medication_id: '', dosage: '', pack_limit: '1', instructions: '', issued_date: '' };
const APPT_TYPE_LABEL = { consultation: 'Consultation', follow_up: 'Follow-up', triage_escalation: 'Escalated' };

const DoctorPrescriptions = () => {
  const { data: prescriptions, isLoading, error, currentPage, totalPages, totalItems, pageSize, setPage, refetch } = usePaginatedFetch(getDoctorPrescriptions);
  const [modalOpen, setModalOpen] = useState(false);
  const [saving, setSaving] = useState(false);
  const [form, setForm] = useState(emptyForm);

  const [completedAppointments, setCompletedAppointments] = useState([]);
  const [allMedications, setAllMedications] = useState([]);

  useEffect(() => {
    getDoctorAppointments({ status: 'completed', limit: 200 })
      .then((res) => setCompletedAppointments(res.data?.data || []))
      .catch(() => {});
    getMedications({ limit: 200 })
      .then((res) => setAllMedications(res.data?.data || []))
      .catch(() => {});
  }, []);

  const appointmentOptions = completedAppointments.map((a) => ({
    value: a.id,
    label: `${a.patient_name || `Patient #${a.patient_id}`} — #${a.id}`,
    sublabel: [
      a.appointment_date ? format(new Date(a.appointment_date), 'dd MMM yyyy') : null,
      a.appointment_start_time ? a.appointment_start_time.slice(0, 5) : null,
      APPT_TYPE_LABEL[a.appointment_type] || null,
    ].filter(Boolean).join(' · '),
  }));

  const medicationOptions = allMedications.map((m) => ({
    value: m.id,
    label: m.name,
    sublabel: `${m.type === 'prescription' ? 'Rx' : 'OTC'} · MYR ${parseFloat(m.price).toFixed(2)}`,
  }));

  const openNew = () => {
    setForm(emptyForm);
    setModalOpen(true);
  };

  const onSubmit = async () => {
    if (!form.appointment_id || !form.medication_id || !form.dosage || !form.issued_date) {
      toast.error('Patient appointment, medication, dosage, and issued date are required.');
      return;
    }
    setSaving(true);
    try {
      await addAppointmentPrescription(form.appointment_id, {
        medication_id: form.medication_id,
        dosage: form.dosage,
        pack_limit: form.pack_limit || 0,
        instructions: form.instructions,
        issued_date: form.issued_date,
      });
      toast.success('Prescription created');
      setModalOpen(false);
      refetch();
    } catch (err) {
      toast.error(err.response?.data?.error || 'Failed to create prescription');
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="animate-fade-in space-y-6">
      <PageHeader
        title="Prescriptions"
        action={
          <Button onClick={openNew}>
            <Plus size={16} />
            New Prescription
          </Button>
        }
      />

      <Card>
        {isLoading && (
          <div className="flex justify-center py-12">
            <Spinner size="lg" />
          </div>
        )}
        {error && <ErrorState message={error} onRetry={refetch} />}
        {!isLoading && !error && prescriptions.length === 0 && <EmptyState icon={Pill} title="No prescriptions" description="Create a prescription for a patient after completing an appointment." />}
        {!isLoading && !error && prescriptions.length > 0 && (
          <div className="space-y-3">
            {prescriptions.map((rx) => (
              <div key={rx.id} className="p-4 rounded-xl bg-surface-subtle hover:bg-surface-warm transition-colors flex items-start gap-4">
                <div className="w-[46px] h-[46px] rounded-xl bg-green-100 flex items-center justify-center flex-shrink-0">
                  <Pill size={22} className="text-green-600" />
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-start justify-between gap-2 mb-1">
                    <p className="text-[15px] font-bold text-text-primary">{rx.medication}</p>
                    <Button variant="ghost" size="sm" onClick={() => downloadPrescription(rx)} className="hover:bg-brand-50 hover:text-brand-700">
                      <Download size={14} />
                      Download
                    </Button>
                  </div>
                  <p className="text-sm text-text-secondary font-medium">{rx.dosage}</p>
                  {rx.instructions && <p className="text-sm text-text-secondary mt-1">{rx.instructions}</p>}
                  <div className="flex items-center gap-3 mt-2 text-xs text-text-muted">
                    <span>Patient: {rx.patient_name || `#${rx.appointment_id}`}</span>
                    <span>•</span>
                    <span>Issued: {rx.issued_date ? format(new Date(rx.issued_date), 'dd MMM yyyy') : '—'}</span>
                    {rx.pack_limit != null && (
                      <>
                        <span>•</span>
                        <span>Refills: {rx.refills_used ?? 0}/{rx.pack_limit}</span>
                      </>
                    )}
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
        <Pagination currentPage={currentPage} totalPages={totalPages} totalItems={totalItems} pageSize={pageSize} onPageChange={setPage} />
      </Card>

      <Modal
        isOpen={modalOpen}
        onClose={() => setModalOpen(false)}
        title="New Prescription"
        footer={
          <>
            <Button variant="secondary" onClick={() => setModalOpen(false)}>
              Cancel
            </Button>
            <Button onClick={onSubmit} isLoading={saving}>
              Save
            </Button>
          </>
        }
      >
        <div className="space-y-4">
          <SearchableSelect
            label="Patient / Appointment"
            options={appointmentOptions}
            value={form.appointment_id}
            onChange={(v) => setForm((p) => ({ ...p, appointment_id: v }))}
            placeholder="Search completed appointments…"
            emptyText="No completed appointments found"
          />
          <SearchableSelect
            label="Medication"
            options={medicationOptions}
            value={form.medication_id}
            onChange={(v) => setForm((p) => ({ ...p, medication_id: v }))}
            placeholder="Search medications (Rx or OTC)…"
            emptyText="No medications found"
          />
          <Input label="Dosage" placeholder="e.g. 500mg twice daily" value={form.dosage} onChange={(e) => setForm((p) => ({ ...p, dosage: e.target.value }))} />
          <Input label="Refills Allowed" type="number" min="0" placeholder="e.g. 2" value={form.pack_limit} onChange={(e) => setForm((p) => ({ ...p, pack_limit: e.target.value }))} />
          <Input label="Instructions" placeholder="Take with food" value={form.instructions} onChange={(e) => setForm((p) => ({ ...p, instructions: e.target.value }))} />
          <Input label="Issued Date" type="date" value={form.issued_date} onChange={(e) => setForm((p) => ({ ...p, issued_date: e.target.value }))} />
        </div>
      </Modal>
    </div>
  );
};

export default DoctorPrescriptions;
