// Field helpers
const t   = (name, label, type = 'text')              => ({ name, label, type });
const num = (name, label)                              => ({ name, label, type: 'number' });
const dt  = (name, label)                              => ({ name, label, type: 'date' });
const ti  = (name, label)                              => ({ name, label, type: 'time' });
const ta  = (name, label)                              => ({ name, label, type: 'textarea' });
const sel = (name, label, options)                     => ({ name, label, type: 'select', options });
const bool = (name, label)                             => sel(name, label, ['true', 'false']);
const dtt = (name, label)                              => ({ name, label, type: 'datetime-local' });

export const ENTITIES = [
  {
    key: 'users',
    label: 'Users',
    fields: [
      t('full_name', 'Full Name'),
      t('email', 'Email', 'email'),
      t('password', 'Password'),
      sel('role', 'Role', ['patient', 'doctor', 'admin']),
      t('phone', 'Phone'),
      sel('gender', 'Gender', ['male', 'female', 'other']),
      dt('date_of_birth', 'Date of Birth'),
      t('profile_picture_url', 'Profile Picture URL'),
      num('login_attempts', 'Login Attempts'),
      dtt('locked_until', 'Locked Until'),
    ],
  },
  {
    key: 'doctors',
    label: 'Doctors',
    fields: [
      num('user_id', 'User ID'),
      t('specialization', 'Specialization'),
      ta('qualifications', 'Qualifications'),
      sel('availability_status', 'Availability', ['available', 'unavailable']),
      t('profile_picture_url', 'Profile Picture URL'),
      ta('bio', 'Bio'),
    ],
  },
  {
    key: 'patients',
    label: 'Patients',
    fields: [
      num('user_id', 'User ID'),
      t('blood_group', 'Blood Group'),
      t('emergency_contact_name', 'Emergency Contact Name'),
      t('emergency_contact_phone', 'Emergency Contact Phone'),
      ta('address', 'Address'),
      ta('allergies', 'Allergies'),
      ta('chronic_conditions', 'Chronic Conditions'),
    ],
  },
  {
    key: 'appointments',
    label: 'Appointments',
    fields: [
      num('patient_id', 'Patient ID'),
      num('doctor_id', 'Doctor ID'),
      dt('appointment_date', 'Appointment Date'),
      ti('appointment_start_time', 'Start Time'),
      ti('appointment_end_time', 'End Time'),
      sel('status', 'Status', ['pending', 'confirmed', 'completed', 'cancelled', 'missed']),
      ta('notes', 'Notes'),
      sel('appointment_type', 'Appointment Type', ['consultation', 'follow_up', 'triage_escalation']),
      num('triage_session_id', 'Triage Session ID'),
      num('created_by', 'Created By (User ID)'),
      bool('reminder_sent', 'Reminder Sent'),
    ],
  },
  {
    key: 'doctor-time-slots',
    label: 'Doctor Time Slots',
    fields: [
      num('doctor_id', 'Doctor ID'),
      sel('day_of_week', 'Day', ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']),
      ti('start_time', 'Start Time'),
      ti('end_time', 'End Time'),
    ],
  },
  {
    key: 'appointment-status-logs',
    label: 'Appt. Status Logs',
    fields: [
      num('appointment_id', 'Appointment ID'),
      t('old_status', 'Old Status'),
      t('new_status', 'New Status'),
    ],
  },
  {
    key: 'prescriptions',
    label: 'Prescriptions',
    fields: [
      num('appointment_id', 'Appointment ID'),
      num('medication_id', 'Medication ID'),
      t('dosage', 'Dosage'),
      ta('instructions', 'Instructions'),
      dt('issued_date', 'Issued Date'),
      num('refills_used', 'Refills Used'),
      num('pack_limit', 'Pack Limit'),
      bool('limit_reached', 'Limit Reached'),
    ],
  },
  {
    key: 'medical-records',
    label: 'Medical Records',
    fields: [
      num('patient_id', 'Patient ID'),
      num('doctor_id', 'Doctor ID'),
      num('appointment_id', 'Appointment ID'),
      t('record_type', 'Record Type'),
      ta('description', 'Description'),
      t('file_url', 'File URL'),
      bool('private', 'Private'),
    ],
  },
  {
    key: 'bills',
    label: 'Bills',
    fields: [
      num('patient_id', 'Patient ID'),
      num('amount', 'Amount'),
      sel('status', 'Status', ['pending', 'paid', 'unpaid', 'overdue', 'cancelled']),
      dt('billing_date', 'Billing Date'),
      ta('details', 'Details'),
      t('currency', 'Currency'),
      num('pharmacy_order_id', 'Pharmacy Order ID'),
    ],
  },
  {
    key: 'plans',
    label: 'Plans',
    fields: [
      t('name', 'Name'),
      ta('description', 'Description'),
      num('price', 'Price'),
      num('duration_days', 'Duration (days)'),
      ta('features', 'Features (JSON)'),
      t('currency', 'Currency'),
    ],
  },
  {
    key: 'subscriptions',
    label: 'Subscriptions',
    fields: [
      num('patient_id', 'Patient ID'),
      t('plan_name', 'Plan Name'),
      dt('start_date', 'Start Date'),
      dt('end_date', 'End Date'),
      bool('auto_renew', 'Auto Renew'),
      sel('status', 'Status', ['active', 'insurance_pending', 'cancelled', 'expired']),
    ],
  },
  {
    key: 'messages',
    label: 'Messages',
    fields: [
      num('conversation_id', 'Conversation ID'),
      num('sender_id', 'Sender ID'),
      ta('message', 'Message'),
      t('attachment_url', 'Attachment URL'),
      sel('attachment_type', 'Attachment Type', ['image', 'pdf']),
    ],
  },
  {
    key: 'notifications',
    label: 'Notifications',
    fields: [
      num('user_id', 'User ID'),
      t('title', 'Title'),
      ta('body', 'Body'),
      bool('is_read', 'Is Read'),
      t('type', 'Type'),
      t('category', 'Category'),
      t('actor_name', 'Actor Name'),
      t('actor_role', 'Actor Role'),
    ],
  },
  {
    key: 'medications',
    label: 'Medications',
    fields: [
      t('name', 'Name'),
      sel('type', 'Type', ['countertop', 'prescription']),
      ta('description', 'Description'),
      num('price', 'Price'),
      t('photo_url', 'Photo URL'),
    ],
  },
  {
    key: 'pharmacy-orders',
    label: 'Pharmacy Orders',
    fields: [
      num('patient_id', 'Patient ID'),
      num('prescription_id', 'Prescription ID'),
      t('medications', 'Medications (comma-separated)'),
      t('quantities', 'Quantities (comma-separated)'),
      num('total_amount', 'Total Amount'),
      t('currency', 'Currency'),
      sel('status', 'Status', ['pending', 'processing', 'dispatched', 'delivered', 'cancelled']),
      t('prescription_file', 'Prescription File'),
      ta('delivery_address', 'Delivery Address'),
      t('payment_method', 'Payment Method'),
      num('insurance_request_id', 'Insurance Request ID'),
    ],
  },
  {
    key: 'question-bank',
    label: 'Question Bank',
    fields: [
      ta('question_text', 'Question Text'),
      sel('question_type', 'Question Type', ['public', 'specialty']),
      t('specialty', 'Specialty'),
      num('suggested_by', 'Suggested By (User ID)'),
      bool('is_approved', 'Is Approved'),
    ],
  },
  {
    key: 'patient-question-responses',
    label: 'Patient Responses',
    fields: [
      num('patient_id', 'Patient ID'),
      num('question_id', 'Question ID'),
      ta('answer', 'Answer'),
    ],
  },
  {
    key: 'doctor-response-notes',
    label: 'Doctor Notes',
    fields: [
      num('doctor_id', 'Doctor ID'),
      num('response_id', 'Response ID'),
      ta('note', 'Note'),
    ],
  },
  {
    key: 'doctor-plans',
    label: 'Doctor Plans',
    fields: [
      t('name', 'Name'),
      ta('description', 'Description'),
      num('monthly_price', 'Monthly Price'),
      num('yearly_price', 'Yearly Price'),
      ta('features', 'Features (JSON)'),
      t('currency', 'Currency'),
    ],
  },
  {
    key: 'doctor-subscriptions',
    label: 'Doctor Subscriptions',
    fields: [
      num('user_id', 'User ID'),
      num('plan_id', 'Plan ID'),
      sel('billing_cycle', 'Billing Cycle', ['monthly', 'yearly']),
      sel('status', 'Status', ['pending', 'approved', 'rejected', 'cancelled', 'paid']),
      t('paperwork_url', 'Paperwork URL'),
      dt('start_date', 'Start Date'),
      dt('end_date', 'End Date'),
      ta('admin_notes', 'Admin Notes'),
    ],
  },
  {
    key: 'insurance-requests',
    label: 'Insurance Requests',
    fields: [
      num('patient_id', 'Patient ID'),
      num('doctor_id', 'Doctor ID'),
      num('bill_id', 'Bill ID'),
      t('insurance_company', 'Insurance Company'),
      t('insurance_id_number', 'Insurance ID Number'),
      dt('start_date', 'Start Date'),
      dt('end_date', 'End Date'),
      sel('status', 'Status', ['pending', 'accepted', 'rejected']),
      num('reviewed_by', 'Reviewed By (User ID)'),
    ],
  },
  {
    key: 'support-tickets',
    label: 'Support Tickets',
    fields: [
      num('user_id', 'User ID'),
      sel('category', 'Category', ['Technical', 'Medical', 'Billing', 'Appointments', 'Other']),
      t('subject', 'Subject'),
      ta('description', 'Description'),
      sel('status', 'Status', ['pending', 'open', 'in progress', 'resolved', 'closed']),
      t('file_url', 'File URL'),
      num('doctor_assigned', 'Doctor Assigned (ID)'),
      num('patient_assigned', 'Patient Assigned (ID)'),
    ],
  },
  {
    key: 'support-ticket-replies',
    label: 'Ticket Replies',
    fields: [
      num('ticket_id', 'Ticket ID'),
      num('user_id', 'User ID'),
      ta('message', 'Message'),
      t('file_url', 'File URL'),
    ],
  },
  {
    key: 'services',
    label: 'Services',
    fields: [
      t('name', 'Name'),
      ta('description', 'Description'),
      num('cost', 'Cost'),
    ],
  },
  {
    key: 'health-programs',
    label: 'Health Programs',
    fields: [
      t('name', 'Name'),
      ta('description', 'Description'),
      dt('start_date', 'Start Date'),
      dt('end_date', 'End Date'),
      ta('eligibility', 'Eligibility'),
    ],
  },
  {
    key: 'health-logs',
    label: 'Health Logs',
    fields: [
      num('patient_id', 'Patient ID'),
      sel('log_type', 'Log Type', ['vitals', 'symptom_update', 'medication_adherence', 'general']),
      ta('data', 'Data (JSON)'),
      ta('notes', 'Notes'),
    ],
  },
  {
    key: 'patient-insurance',
    label: 'Patient Insurance',
    fields: [
      num('patient_id', 'Patient ID'),
      t('insurance_company', 'Insurance Company'),
      t('insurance_id_number', 'Insurance ID Number'),
      dt('start_date', 'Start Date'),
      dt('end_date', 'End Date'),
      bool('is_active', 'Is Active'),
    ],
  },
  {
    key: 'payment-methods',
    label: 'Payment Methods',
    fields: [
      num('user_id', 'User ID'),
      sel('provider', 'Provider', ['card', 'fpx']),
      t('cardholder_name', 'Cardholder Name'),
      t('brand', 'Brand'),
      t('last4', 'Last 4 Digits'),
      num('exp_month', 'Expiry Month'),
      num('exp_year', 'Expiry Year'),
      sel('status', 'Status', ['active', 'inactive']),
      bool('is_default', 'Is Default'),
    ],
  },
  {
    key: 'payment-transactions',
    label: 'Payment Transactions',
    fields: [
      num('user_id', 'User ID'),
      num('bill_id', 'Bill ID'),
      num('doctor_subscription_id', 'Doctor Subscription ID'),
      num('amount', 'Amount'),
      t('currency', 'Currency'),
      sel('method_type', 'Method Type', ['card', 'fpx']),
      t('fpx_bank', 'FPX Bank'),
      num('payment_method_id', 'Payment Method ID'),
      t('transaction_ref', 'Transaction Reference'),
      sel('status', 'Status', ['success', 'failed', 'pending']),
    ],
  },
  {
    key: 'billing-addresses',
    label: 'Billing Addresses',
    fields: [
      num('user_id', 'User ID'),
      sel('addr_type', 'Address Type', ['billing', 'shipping']),
      t('first_name', 'First Name'),
      t('last_name', 'Last Name'),
      t('line1', 'Address Line 1'),
      t('line2', 'Address Line 2'),
      t('city', 'City'),
      t('region', 'Region'),
      t('postal_code', 'Postal Code'),
      t('country_code', 'Country Code'),
      t('email', 'Email', 'email'),
      t('phone', 'Phone'),
      bool('is_default', 'Is Default'),
    ],
  },
  {
    key: 'conversations',
    label: 'Conversations',
    fields: [
      t('title', 'Title'),
      bool('is_group', 'Is Group'),
      num('created_by', 'Created By (User ID)'),
    ],
  },
  {
    key: 'conversation-participants',
    label: 'Conversation Participants',
    fields: [
      num('conversation_id', 'Conversation ID'),
      num('user_id', 'User ID'),
      bool('is_pinned', 'Is Pinned'),
    ],
  },
  {
    key: 'question-assignments',
    label: 'Question Assignments',
    fields: [
      num('question_id', 'Question ID'),
      num('patient_id', 'Patient ID'),
      num('doctor_id', 'Doctor ID'),
      num('response_id', 'Response ID'),
    ],
  },
  {
    key: 'triage-sessions',
    label: 'Triage Sessions',
    fields: [
      num('patient_id', 'Patient ID'),
      ta('symptoms_text', 'Symptoms'),
      sel('urgency_level', 'Urgency Level', ['emergency', 'urgent', 'standard', 'self_care']),
      ta('recommended_action', 'Recommended Action'),
      t('recommended_department', 'Recommended Department'),
      bool('follow_up_recommended', 'Follow-Up Recommended'),
      num('escalated_to_doctor_id', 'Escalated To Doctor (ID)'),
    ],
  },
  {
    key: 'triage-symptom-rules',
    label: 'Triage Symptom Rules',
    fields: [
      sel('urgency_level', 'Urgency Level', ['emergency', 'urgent', 'standard', 'self_care']),
      ta('keywords', 'Keywords (comma-separated)'),
      ta('recommended_action', 'Recommended Action'),
      t('recommended_department', 'Recommended Department'),
    ],
  },
];
